name: Flutter Workflow

on: pull_request
jobs:
  build:
    name: Build and Tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.18.1"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage
